---
title: "HW_2_Patutina"
author: "Patutina Ekaterina, 175"
date: "2/12/2021"
output: pdf_document
---
## Assignment 1,2
```{r}
library(network)
drugpaj <- read.paj('drugnet2.paj')
drug <- drugpaj$networks[[1]] # Extract network
plot(drug)
#check what attributes we have and lets extract them
names(drugpaj$partitions)
gender <- drugpaj$partitions[[1]]
ethnicity <- drugpaj$partitions[[2]]
drug <-set.vertex.attribute(drug, 'gender', value=c(gender))
drug <-set.vertex.attribute(drug, 'ethnicity', value=c(ethnicity))
gender <- drugpaj$partitions[[1]]
colors1 <- ifelse(gender == 1,'cadetblue' , ifelse(gender == 2, 'indianred', 'grey'))
plot(drug, vertex.col = colors1)

colors2 <- ifelse(ethnicity ==1,'grey' , ifelse(ethnicity == 2, 'indianred', ifelse(ethnicity == 0,'green','cadetblue')))
plot(drug, vertex.col = colors2)

```
As a result we see that men are more prone to be in the center of the network.
And what is more interesting people of one ethnicity are more prone to have deals with their ethnicity. There are 2 big clusters, and both of them have ethnicity majority, but ethnicity are different.

## Assignment 3
```{r}
load('madmen.Rdata')
mad.net <- as.network(mad.matrix, directed=FALSE)
set.vertex.attribute(mad.net,attrname='female', value=mad.att[,2])
coordkk<-network.layout.kamadakawai(mad.net,mad.att)
plot(mad.net, coord = coordkk)
coordfr<-network.layout.fruchtermanreingold(mad.net,mad.att)
plot(mad.net, coord = coordfr)
coordcr<-network.layout.circle(mad.net,mad.att)
if_female= ifelse(mad.att$Female == 1, 'pink', 'blue')
plot(mad.net, vertex.cex=2, vertex.col = if_female, coord = coordfr, displaylabels=TRUE,label.cex=0.5, main = 'The sexual network of the TV show “Mad Men"')
edge_number = c()
for (i in 1:length(mad.matrix[,1])) {
  tmp = 0
  tmp = sum(c(mad.matrix[,i]))
  tmp = sqrt(tmp) + 1
  edge_number = c(edge_number, tmp)
}
edge_number
plot(mad.net, vertex.cex=edge_number, vertex.col = if_female, coord = coordfr, displaylabels=TRUE,label.cex=0.5, main = 'The sexual network of the TV show “Mad Men"')
```
